### ISSUE TITLE
How to set bit depth? Can't find it under sox.Output...

### ISSUE THREAD

**Issue by theonlygusti** [igece/SoxSharp#15]

**Comment by theonlygusti** [comment]
I found a AudioInfo.SampleSize

I think the only way to change the output's bit depth, channels etc. is directly passing the command line args?

**Comment by theonlygusti** [comment]
I found a AudioInfo.SampleSize

I think the only way to change the output's bit depth, channels etc. is directly passing the command line args?

**Comment by igece** [comment]
What you're looking for is `Output.SampleSize`. However, I just found that settings this value has no effect on the output command string, so it needs to be fixed. Until then, you can use `Output.CustomArgs`.

To change the number of output channels, use `Output.Channels` property.

**Comment by theonlygusti** [comment]
How long might it take for this to be fixed in the library?
